version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Deploy to Vercel
          command: |
            npm install -g vercel
            vercel --prod --token $VERCEL_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
