version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Deploy to Vercel
          command: npx vercel --prod --token $VERCEL_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
